steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/dotnet-cicd-422508/gke-repo/blazor-app', './app1' ]
  id: 'Build Docker Image'

  # images:
  # - 'us-central1-docker.pkg.dev/<your_project_id>/gke-repo/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/dotnet-cicd-422508/gke-repo/blazor-app' ]
  id: 'Push Docker Image'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials "cluster-1" --zone "us-central1-c" --project "dotnet-cicd-422508"

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'deployment/blazor.yaml']
  args: ['apply', '-f', 'deployment/ingress.yaml']
  args: ['apply', '-f', 'deployment/service.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
