apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor-app
  template:
    metadata:
      labels:
        app: blazor-app
    spec:
      containers:
        - name: blazor-app
          image: us-central1-docker.pkg.dev/dotnet-cicd-422508/gke-repo/blazor-app
          ports:
            - containerPort: 80
