apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor-app
  template:
    metadata:
      labels:
        app: blazor-app
    spec:
      containers:
        - name: blazor-app
          image: regdemo3.azurecr.io/blazor-app
          ports:
            - containerPort: 80
